version: "3"

services:
  web:

    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DOCKER=TRUE
    depends_on:
      - redis
      - memcached

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  memcached:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - "11211:11211"
    restart: always